package com.citihive.payvote.entity;
/**
 * @author Sreekanth Varidhireddy
 * Sep 18, 2023
 */
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName="voter")
public class Voter {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String voterID;
	
	@DynamoDBAttribute
	private String voterFirstname;
	@DynamoDBAttribute
	private String voterLastname;
	
	@DynamoDBAttribute
	private String voterTitle;
	
	@DynamoDBAttribute
	private String voterEmail;
	
	@DynamoDBAttribute
	private Boolean isUSCitizen;
	
	@DynamoDBAttribute
	private String address;
	
	@DynamoDBAttribute
	private String unit;
	
	@DynamoDBAttribute
	private String city;
	
	@DynamoDBAttribute
	private String state;
	
	@DynamoDBAttribute
	private String zipcode;
	
	@DynamoDBAttribute
	private Boolean hasID;
	
	@DynamoDBAttribute
	private Date dob;
	
	@DynamoDBAttribute
	private String phone1;
	
	@DynamoDBAttribute
	private String phone2;
	
	@DynamoDBAttribute
	private RegistrationStatus registrationStatus;
	
	

}
